import { Pencil, Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';

import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Switch } from '../../components/ui/switch';
import { useToast } from '../../components/ui/toast';
import { cn } from '../../lib/utils';
import { useModelCardsStore, type ModelPreset } from '../../stores/model-cards-store';

/**
 * The channel form's model picker.
 *
 * Every model the channel advertises gets a card — whether it came from the
 * catalogue or was already saved on the channel — so the picker can never hide
 * part of what the channel actually serves. The cards read and rewrite the
 * `models` / `modelMapping` form fields rather than keeping their own copy,
 * which is why the two views cannot disagree.
 *
 * The `alias -> upstream` syntax is generated by the form and never shown;
 * the operator is told what will happen in a sentence instead.
 */

interface CardDraft {
  alias: string;
  hint: string;
}

/** Rejects a name that could not survive a round trip through the mapping. */
function aliasError(alias: string, taken: string[]): string | null {
  if (alias === '') return 'اكتب اسم النموذج كما يرسله العميل';
  if (/\s/.test(alias)) return 'اسم النموذج لا يقبل مسافات';
  if (alias.includes('->')) return 'لا يمكن أن يحتوي الاسم على السهم ->';
  if (taken.includes(alias)) return 'هذا النموذج موجود بالفعل';
  return null;
}

interface ModelCardsProps {
  /** Names this channel currently advertises. */
  models: string[];
  mapping: Record<string, string>;
  /** Toggle a card on or off. `upstreamModel` is the id the provider expects. */
  onToggle: (alias: string, active: boolean, upstreamModel: string) => void;
  /** Rename a model, carrying its mapping across under the new name. */
  onRename: (from: string, to: string) => void;
}

export function ModelCards({ models, mapping, onToggle, onRename }: ModelCardsProps) {
  const toast = useToast();

  const cards = useModelCardsStore((state) => state.cards);
  const addCard = useModelCardsStore((state) => state.addCard);
  const updateCard = useModelCardsStore((state) => state.updateCard);
  const removeCard = useModelCardsStore((state) => state.removeCard);

  const [draft, setDraft] = useState<CardDraft | null>(null);
  const [editing, setEditing] = useState<(CardDraft & { original: string }) | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [confirming, setConfirming] = useState<string | null>(null);

  const catalogued = new Set(cards.map((card) => card.alias));
  const extras: ModelPreset[] = models
    .filter((alias) => !catalogued.has(alias))
    .map((alias) => ({ alias, hint: 'مُضاف على هذه القناة' }));
  const visible: ModelPreset[] = [...cards, ...extras];

  const closeForms = () => {
    setDraft(null);
    setEditing(null);
    setError(null);
  };

  const submitDraft = () => {
    if (draft === null) return;
    const alias = draft.alias.trim();
    const problem = aliasError(alias, visible.map((card) => card.alias));
    if (problem !== null) {
      setError(problem);
      return;
    }
    addCard({ alias, hint: draft.hint.trim() || 'نموذج مخصّص' });
    onToggle(alias, true, alias);
    toast.success(`أُضيف «${alias}» وفُعّل على هذه القناة`);
    closeForms();
  };

  const submitEdit = () => {
    if (editing === null) return;
    const alias = editing.alias.trim();
    const others = visible.map((card) => card.alias).filter((name) => name !== editing.original);
    const problem = aliasError(alias, others);
    if (problem !== null) {
      setError(problem);
      return;
    }
    const next = { alias, hint: editing.hint.trim() || 'نموذج مخصّص' };
    if (alias !== editing.original) onRename(editing.original, alias);
    // Editing a model that only lived on this channel promotes it to the
    // catalogue, so its description survives instead of being reset.
    if (catalogued.has(editing.original)) updateCard(editing.original, next);
    else addCard(next);
    toast.success('تم حفظ البطاقة');
    closeForms();
  };

  const confirmDelete = (alias: string) => {
    const attached = models.includes(alias);
    if (attached) onToggle(alias, false, '');
    removeCard(alias);
    setConfirming(null);
    toast.success(attached ? `حُذفت البطاقة وأُزيل «${alias}» من القناة` : 'تم حذف البطاقة');
  };

  return (
    <div className="space-y-3">
      <div className="grid gap-2 sm:grid-cols-2">
        {visible.map((card) => {
          const active = models.includes(card.alias);
          const upstream = mapping[card.alias] ?? '';
          const rewritten = upstream.trim() !== '' && upstream.trim() !== card.alias;

          if (confirming === card.alias) {
            return (
              <div
                key={card.alias}
                className="rounded-lg border border-destructive/40 bg-destructive/5 p-3"
              >
                <p className="text-sm font-medium" dir="ltr">
                  حذف «{card.alias}»؟
                </p>
                <p className="mt-1 text-xs text-muted-foreground">
                  {active
                    ? 'ستُزال البطاقة من القائمة ويُلغى تفعيل النموذج على هذه القناة.'
                    : 'ستُزال البطاقة من القائمة.'}
                </p>
                <div className="mt-3 flex gap-2">
                  <Button size="sm" variant="destructive" onClick={() => confirmDelete(card.alias)}>
                    حذف
                  </Button>
                  <Button size="sm" variant="outline" onClick={() => setConfirming(null)}>
                    إلغاء
                  </Button>
                </div>
              </div>
            );
          }

          if (editing?.original === card.alias) {
            return (
              <div key={card.alias} className="space-y-2 rounded-lg border border-border p-3">
                <Input
                  dir="ltr"
                  className="h-8 text-xs"
                  value={editing.alias}
                  autoFocus
                  onChange={(event) => setEditing({ ...editing, alias: event.target.value })}
                  placeholder="claude-3-5-sonnet"
                  aria-label="اسم النموذج"
                />
                <Input
                  className="h-8 text-xs"
                  value={editing.hint}
                  onChange={(event) => setEditing({ ...editing, hint: event.target.value })}
                  placeholder="وصف مختصر يظهر على البطاقة"
                  aria-label="وصف البطاقة"
                />
                {error !== null ? <p className="text-[11px] text-destructive">{error}</p> : null}
                <div className="flex gap-2">
                  <Button size="sm" onClick={submitEdit}>
                    حفظ
                  </Button>
                  <Button size="sm" variant="outline" onClick={closeForms}>
                    إلغاء
                  </Button>
                </div>
              </div>
            );
          }

          return (
            <div
              key={card.alias}
              className={cn(
                'rounded-lg border p-3 transition-colors duration-150',
                active ? 'border-success/40 bg-accent/30' : 'border-border',
              )}
            >
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <p className="truncate text-sm font-medium" dir="ltr">
                    {card.alias}
                  </p>
                  <p className="mt-0.5 text-xs text-muted-foreground">{card.hint}</p>
                </div>

                <div className="flex shrink-0 items-center gap-1">
                  <Button
                    variant="ghost"
                    size="icon"
                    className="size-7"
                    onClick={() => {
                      setError(null);
                      setDraft(null);
                      setEditing({ original: card.alias, alias: card.alias, hint: card.hint });
                    }}
                    aria-label={`تعديل ${card.alias}`}
                    title="تعديل"
                  >
                    <Pencil className="size-3.5" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="size-7 hover:text-destructive"
                    onClick={() => setConfirming(card.alias)}
                    aria-label={`حذف ${card.alias}`}
                    title="حذف"
                  >
                    <Trash2 className="size-3.5" />
                  </Button>
                  <Switch
                    checked={active}
                    onCheckedChange={(next) => onToggle(card.alias, next, upstream || card.alias)}
                    aria-label={active ? `إيقاف ${card.alias}` : `تشغيل ${card.alias}`}
                  />
                </div>
              </div>

              {active ? (
                <div className="mt-3 space-y-1.5">
                  <label
                    htmlFor={`upstream-${card.alias}`}
                    className="block text-xs text-muted-foreground"
                  >
                    اسمه عند المزوّد
                  </label>
                  <Input
                    id={`upstream-${card.alias}`}
                    dir="ltr"
                    className="h-8 text-xs"
                    value={upstream}
                    placeholder={card.alias}
                    onChange={(event) => onToggle(card.alias, true, event.target.value)}
                  />
                  {/* What the mapping will do, without exposing its syntax. */}
                  <p className="truncate text-[11px] text-muted-foreground">
                    {rewritten
                      ? `يُحوَّل تلقائياً إلى ${upstream.trim()}`
                      : 'يُرسل الاسم كما هو'}
                  </p>
                </div>
              ) : null}
            </div>
          );
        })}
      </div>

      {draft === null ? (
        <Button
          variant="outline"
          size="sm"
          onClick={() => {
            setError(null);
            setEditing(null);
            setDraft({ alias: '', hint: '' });
          }}
        >
          <Plus />
          إضافة بطاقة جديدة
        </Button>
      ) : (
        <div className="space-y-2 rounded-lg border border-dashed border-border p-3">
          <Input
            dir="ltr"
            className="h-8 text-xs"
            value={draft.alias}
            autoFocus
            onChange={(event) => setDraft({ ...draft, alias: event.target.value })}
            placeholder="claude-3-5-sonnet"
            aria-label="اسم النموذج الجديد"
          />
          <Input
            className="h-8 text-xs"
            value={draft.hint}
            onChange={(event) => setDraft({ ...draft, hint: event.target.value })}
            placeholder="وصف مختصر يظهر على البطاقة"
            aria-label="وصف البطاقة"
          />
          {error !== null ? <p className="text-[11px] text-destructive">{error}</p> : null}
          <div className="flex gap-2">
            <Button size="sm" onClick={submitDraft}>
              إضافة وتفعيل
            </Button>
            <Button size="sm" variant="outline" onClick={closeForms}>
              إلغاء
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
