import { getTableColumns, getTableName, is } from 'drizzle-orm';
import { PgTable } from 'drizzle-orm/pg-core';
import { pathToFileURL } from 'node:url';
import { config } from '../config.js';
import { db, pg } from './index.js';
import * as schema from './schema.js';

/**
 * Migrations are applied as explicit DDL rather than generated by a toolkit.
 *
 * The schema is small, stable and owned entirely by this project, and a
 * hand-audited DDL plus a boot-time drift check is stronger than a generated
 * file nobody reads. `verifySchema()` compares the live database against
 * `schema.ts`, so a mismatch between the two fails loudly at startup instead
 * of surfacing as a runtime "column does not exist" hours later.
 *
 * Every statement is idempotent, so running `migrate()` on boot against the
 * same Supabase project is always safe.
 */

/**
 * Schema objects, in dependency order.
 *
 * Existence is checked with `to_regclass()` before each statement runs rather
 * than relying on `IF NOT EXISTS`: creating (or skipping) an index still
 * parses the target table, and Postgres demands ownership of a table owned by
 * another role even when the statement would be a no-op. A dedicated app role
 * therefore migrates a database initialised by the Supabase dashboard without
 * needing to own the tables.
 */
interface SchemaObject {
  /** Relation name in the `public` schema (table or index). */
  name: string;
  ddl: string;
}

const DDL: SchemaObject[] = [
  {
    name: 'channels',
    ddl: `CREATE TABLE IF NOT EXISTS "channels" (
    "id" serial PRIMARY KEY,
    "name" text NOT NULL,
    "type" text NOT NULL,
    "base_url" text NOT NULL,
    "keys" text DEFAULT '[]' NOT NULL,
    "models" text DEFAULT '[]' NOT NULL,
    "model_mapping" text DEFAULT '{}' NOT NULL,
    "group" text DEFAULT 'default' NOT NULL,
    "priority" integer DEFAULT 0 NOT NULL,
    "weight" integer DEFAULT 0 NOT NULL,
    "enabled" boolean DEFAULT true NOT NULL,
    "auth_style" text DEFAULT 'bearer' NOT NULL,
    "extra_headers" text DEFAULT '{}' NOT NULL,
    "status" text DEFAULT 'unknown' NOT NULL,
    "last_latency_ms" integer,
    "last_tested_at" bigint,
    "last_error" text,
    "created_at" bigint DEFAULT (extract(epoch from now()) * 1000)::bigint NOT NULL,
    "updated_at" bigint DEFAULT (extract(epoch from now()) * 1000)::bigint NOT NULL
  )`,
  },
  {
    name: 'idx_channels_enabled',
    ddl: `CREATE INDEX IF NOT EXISTS "idx_channels_enabled" ON "channels" ("enabled")`,
  },
  {
    name: 'abilities',
    ddl: `CREATE TABLE IF NOT EXISTS "abilities" (
    "id" serial PRIMARY KEY,
    "group" text NOT NULL,
    "model" text NOT NULL,
    "channel_id" integer NOT NULL REFERENCES "channels"("id") ON DELETE CASCADE,
    "enabled" boolean DEFAULT true NOT NULL,
    "priority" integer DEFAULT 0 NOT NULL,
    "weight" integer DEFAULT 0 NOT NULL
  )`,
  },
  {
    name: 'idx_abilities_lookup',
    ddl: `CREATE INDEX IF NOT EXISTS "idx_abilities_lookup" ON "abilities" ("group", "model")`,
  },
  {
    name: 'idx_abilities_unique',
    ddl: `CREATE UNIQUE INDEX IF NOT EXISTS "idx_abilities_unique" ON "abilities" ("group", "model", "channel_id")`,
  },
  {
    name: 'api_keys',
    ddl: `CREATE TABLE IF NOT EXISTS "api_keys" (
    "id" serial PRIMARY KEY,
    "name" text NOT NULL,
    "key_hash" text NOT NULL UNIQUE,
    "key_preview" text NOT NULL,
    "group" text DEFAULT 'default' NOT NULL,
    "model_limit" text DEFAULT '[]' NOT NULL,
    "status" text DEFAULT 'active' NOT NULL,
    "expires_at" bigint,
    "last_used_at" bigint,
    "created_at" bigint DEFAULT (extract(epoch from now()) * 1000)::bigint NOT NULL
  )`,
  },
  {
    name: 'idx_api_keys_status',
    ddl: `CREATE INDEX IF NOT EXISTS "idx_api_keys_status" ON "api_keys" ("status")`,
  },
  {
    name: 'request_logs',
    ddl: `CREATE TABLE IF NOT EXISTS "request_logs" (
    "id" serial PRIMARY KEY,
    "key_id" integer,
    "key_name" text DEFAULT '' NOT NULL,
    "channel_id" integer,
    "channel_name" text DEFAULT '' NOT NULL,
    "model" text NOT NULL,
    "upstream_model" text DEFAULT '' NOT NULL,
    "client_format" text NOT NULL,
    "upstream_format" text DEFAULT '' NOT NULL,
    "prompt_tokens" integer DEFAULT 0 NOT NULL,
    "completion_tokens" integer DEFAULT 0 NOT NULL,
    "cached_tokens" integer DEFAULT 0 NOT NULL,
    "total_tokens" integer DEFAULT 0 NOT NULL,
    "status_code" integer DEFAULT 0 NOT NULL,
    "ok" boolean DEFAULT false NOT NULL,
    "latency_ms" integer DEFAULT 0 NOT NULL,
    "is_stream" boolean DEFAULT false NOT NULL,
    "error_message" text,
    "created_at" bigint DEFAULT (extract(epoch from now()) * 1000)::bigint NOT NULL
  )`,
  },
  {
    name: 'idx_logs_created',
    ddl: `CREATE INDEX IF NOT EXISTS "idx_logs_created" ON "request_logs" ("created_at")`,
  },
  {
    name: 'idx_logs_model',
    ddl: `CREATE INDEX IF NOT EXISTS "idx_logs_model" ON "request_logs" ("model")`,
  },
  {
    name: 'idx_logs_channel',
    ddl: `CREATE INDEX IF NOT EXISTS "idx_logs_channel" ON "request_logs" ("channel_id")`,
  },
  {
    name: 'settings',
    ddl: `CREATE TABLE IF NOT EXISTS "settings" (
    "key" text PRIMARY KEY NOT NULL,
    "value" text NOT NULL
  )`,
  },
];

/**
 * Columns added after the first release live here.
 *
 * `CREATE TABLE IF NOT EXISTS` cannot change an existing table, so databases
 * created before a column was introduced need it added explicitly. Each ALTER
 * is wrapped in a DO block that swallows exactly the "duplicate column" error
 * and nothing else, making re-runs a no-op.
 */
const ALTERS: string[] = [];

function isTable(value: unknown): value is PgTable {
  return is(value, PgTable);
}

/**
 * Compare the declared schema against the live database.
 * Catches the exact failure mode this design is exposed to: DDL and the Drizzle
 * schema drifting apart.
 */
export async function verifySchema(): Promise<void> {
  const problems: string[] = [];

  for (const [exportName, value] of Object.entries(schema)) {
    if (!isTable(value)) continue;

    const tableName = getTableName(value);
    const declared = Object.values(getTableColumns(value)).map((column) => column.name);
    const rows = (await pg`
      SELECT column_name FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = ${tableName}
    `) as Array<{ column_name: string }>;

    if (rows.length === 0) {
      problems.push(`table "${tableName}" (from export "${exportName}") is missing`);
      continue;
    }

    const actual = new Set(rows.map((row) => row.column_name));
    const missing = declared.filter((column) => !actual.has(column));
    if (missing.length > 0) {
      problems.push(`table "${tableName}" is missing columns: ${missing.join(', ')}`);
    }
  }

  if (problems.length > 0) {
    throw new Error(
      `Database schema does not match src/db/schema.ts:\n  - ${problems.join('\n  - ')}\n` +
        'Run `node scripts/acc.mjs db` to apply the schema, or add a migration.',
    );
  }
}

export async function migrate(): Promise<void> {
  for (const object of DDL) {
    const rows = (await pg`
      SELECT to_regclass('public.' || ${object.name}) AS reg
    `) as Array<{ reg: string | null }>;
    if (rows[0]?.reg !== null && rows[0]?.reg !== undefined) continue;

    await pg.unsafe(object.ddl);
  }
  for (const statement of ALTERS) {
    await pg.unsafe(statement);
  }
  await verifySchema();
}

export { db };

/**
 * Direct execution: `node scripts/acc.mjs db`, or `tsx src/db/migrate.ts`.
 * Imported as a module, this file only defines `migrate()`.
 *
 * The comparison goes through `pathToFileURL` because a Windows path such as
 * `C:\repo\server\src\db\migrate.ts` is not a valid `file://` URL as written.
 */
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  migrate()
    .then(() => {
      console.log('[db] schema up to date on the Supabase database');
      return pg.end();
    })
    .then(() => process.exit(0))
    .catch((error) => {
      console.error('[db] migration failed:', error instanceof Error ? error.message : error);
      process.exit(1);
    });
}
