import { getTableColumns, getTableName, is } from 'drizzle-orm';
import { SQLiteTable } from 'drizzle-orm/sqlite-core';
import { pathToFileURL } from 'node:url';
import { config } from '../config.js';
import { db, sqliteClient } from './index.js';
import * as schema from './schema.js';

/**
 * Migrations are applied as explicit DDL rather than generated by a toolkit.
 *
 * The schema is small, stable and owned entirely by this project, and a
 * hand-audited DDL plus a boot-time drift check is stronger than a generated
 * file nobody reads. `verifySchema()` below compares the live database against
 * `schema.ts`, so a mismatch between the two fails loudly at startup instead
 * of surfacing as a runtime "no such column" hours later.
 */

const DDL: string[] = [
  `CREATE TABLE IF NOT EXISTS "channels" (
    "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" text NOT NULL,
    "type" text NOT NULL,
    "base_url" text NOT NULL,
    "keys" text DEFAULT '[]' NOT NULL,
    "models" text DEFAULT '[]' NOT NULL,
    "model_mapping" text DEFAULT '{}' NOT NULL,
    "group" text DEFAULT 'default' NOT NULL,
    "priority" integer DEFAULT 0 NOT NULL,
    "weight" integer DEFAULT 0 NOT NULL,
    "enabled" integer DEFAULT 1 NOT NULL,
    "status" text DEFAULT 'unknown' NOT NULL,
    "last_latency_ms" integer,
    "last_tested_at" integer,
    "last_error" text,
    "created_at" integer DEFAULT (unixepoch() * 1000) NOT NULL,
    "updated_at" integer DEFAULT (unixepoch() * 1000) NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "idx_channels_enabled" ON "channels" ("enabled")`,

  `CREATE TABLE IF NOT EXISTS "abilities" (
    "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
    "group" text NOT NULL,
    "model" text NOT NULL,
    "channel_id" integer NOT NULL REFERENCES "channels"("id") ON DELETE CASCADE,
    "enabled" integer DEFAULT 1 NOT NULL,
    "priority" integer DEFAULT 0 NOT NULL,
    "weight" integer DEFAULT 0 NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "idx_abilities_lookup" ON "abilities" ("group", "model")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "idx_abilities_unique" ON "abilities" ("group", "model", "channel_id")`,

  `CREATE TABLE IF NOT EXISTS "api_keys" (
    "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" text NOT NULL,
    "key_hash" text NOT NULL UNIQUE,
    "key_preview" text NOT NULL,
    "group" text DEFAULT 'default' NOT NULL,
    "model_limit" text DEFAULT '[]' NOT NULL,
    "status" text DEFAULT 'active' NOT NULL,
    "expires_at" integer,
    "last_used_at" integer,
    "created_at" integer DEFAULT (unixepoch() * 1000) NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "idx_api_keys_status" ON "api_keys" ("status")`,

  `CREATE TABLE IF NOT EXISTS "request_logs" (
    "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
    "key_id" integer,
    "key_name" text DEFAULT '' NOT NULL,
    "channel_id" integer,
    "channel_name" text DEFAULT '' NOT NULL,
    "model" text NOT NULL,
    "upstream_model" text DEFAULT '' NOT NULL,
    "client_format" text NOT NULL,
    "upstream_format" text DEFAULT '' NOT NULL,
    "prompt_tokens" integer DEFAULT 0 NOT NULL,
    "completion_tokens" integer DEFAULT 0 NOT NULL,
    "cached_tokens" integer DEFAULT 0 NOT NULL,
    "total_tokens" integer DEFAULT 0 NOT NULL,
    "status_code" integer DEFAULT 0 NOT NULL,
    "ok" integer DEFAULT 0 NOT NULL,
    "latency_ms" integer DEFAULT 0 NOT NULL,
    "is_stream" integer DEFAULT 0 NOT NULL,
    "error_message" text,
    "created_at" integer DEFAULT (unixepoch() * 1000) NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS "idx_logs_created" ON "request_logs" ("created_at")`,
  `CREATE INDEX IF NOT EXISTS "idx_logs_model" ON "request_logs" ("model")`,
  `CREATE INDEX IF NOT EXISTS "idx_logs_channel" ON "request_logs" ("channel_id")`,

  `CREATE TABLE IF NOT EXISTS "settings" (
    "key" text PRIMARY KEY NOT NULL,
    "value" text NOT NULL
  )`,
];

function isTable(value: unknown): value is SQLiteTable {
  return is(value, SQLiteTable);
}

/**
 * Compare the declared schema against the live database.
 * Catches the exact failure mode this design is exposed to: DDL and the Drizzle
 * schema drifting apart.
 */
export function verifySchema(): void {
  const problems: string[] = [];

  for (const [exportName, value] of Object.entries(schema)) {
    if (!isTable(value)) continue;

    const tableName = getTableName(value);
    const declared = Object.values(getTableColumns(value)).map((column) => column.name);
    const rows = sqliteClient.prepare(`PRAGMA table_info("${tableName}")`).all() as {
      name: string;
    }[];

    if (rows.length === 0) {
      problems.push(`table "${tableName}" (from export "${exportName}") is missing`);
      continue;
    }

    const actual = new Set(rows.map((row) => row.name));
    const missing = declared.filter((column) => !actual.has(column));
    if (missing.length > 0) {
      problems.push(`table "${tableName}" is missing columns: ${missing.join(', ')}`);
    }
  }

  if (problems.length > 0) {
    throw new Error(
      `Database schema does not match src/db/schema.ts:\n  - ${problems.join('\n  - ')}\n` +
        'Run `node scripts/acc.mjs reset` to recreate it, or add a migration.',
    );
  }
}

export function migrate(): void {
  sqliteClient.exec('BEGIN');
  try {
    for (const statement of DDL) {
      sqliteClient.exec(statement);
    }
    sqliteClient.exec('COMMIT');
  } catch (error) {
    sqliteClient.exec('ROLLBACK');
    throw error;
  }
  verifySchema();
}

export { db };

/**
 * Direct execution: `node scripts/acc.mjs db`, or `tsx src/db/migrate.ts`.
 * Imported as a module, this file only defines `migrate()`.
 *
 * The comparison goes through `pathToFileURL` because a Windows path such as
 * `C:\repo\server\src\db\migrate.ts` is not a valid `file://` URL as written.
 */
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  migrate();
  console.log(`[db] schema up to date at ${config.dbPath}`);
}
